

version: 1.0.0

# Site Settings
locale              : "en-US"
title               : "Pedro D. Marrero"
title_separator     : "-"
name                : &name "Pedro D. Marrero"
tagline             : "D33p L3rn!ng 70r Y0u!!! | Learning to learning."
description         : &description "Site of Pedro D. Marrero Fernandez."
baseurl             : ""
url                 : http://pedrodiamel.github.io
logo                : '/public/logo.png'


# Site Author
author:
  name              : Pedro D. Marrero Fernandez.
  description       : Ph.D in Computer Science and IA / Deep Learning Consultant at <strong>Accenture</strong>.
  gravatar          : 5395ebb7e604036f062a9629d4f4328d # md5 hash of your email address
  contact:
    linkedin        : https://www.linkedin.com/in/pedro-diamel
    github          : https://github.com/pedrodiamel
    twitter         : https://twitter.com/Pedrodiamel
    googlescholar   : https://scholar.google.com/citations?authuser=1&user=g7Vcpe4AAAAJ
    email           : malito:pedrodiamel@gmail.com
    #orcid           : orcid
    # facebook        : face
    # weibo:     http://weibo.com/41173780


markdown: kramdown
# kramdown:
#   input: GFM
# plugins:
#   - jekyll-paginate


excerpt_separator: "<!-- more -->"

sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: /:year-:month-:day-:title/
future: true








# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'http://pedrodiamel.github.io/'


# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image:
  caption:




# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'deeplearningforyou' # leave blank if you don't want disqus
